// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_60000_points = "CgkI09n5uP8HEAIQJg"; // <GPGSID>
        public const string achievement_1000_pillows_every_time = "CgkI09n5uP8HEAIQHA"; // <GPGSID>
        public const string achievement_100_slugs_every_time = "CgkI09n5uP8HEAIQIA"; // <GPGSID>
        public const string achievement_level_30 = "CgkI09n5uP8HEAIQDA"; // <GPGSID>
        public const string achievement_15000_points = "CgkI09n5uP8HEAIQIg"; // <GPGSID>
        public const string achievement_10000_points = "CgkI09n5uP8HEAIQCA"; // <GPGSID>
        public const string achievement_1000_points = "CgkI09n5uP8HEAIQBQ"; // <GPGSID>
        public const string achievement_5_pillows = "CgkI09n5uP8HEAIQFQ"; // <GPGSID>
        public const string achievement_15_rabbits = "CgkI09n5uP8HEAIQEA"; // <GPGSID>
        public const string achievement_15_colored_eggs = "CgkI09n5uP8HEAIQGQ"; // <GPGSID>
        public const string achievement_1000_slugs_every_time = "CgkI09n5uP8HEAIQHQ"; // <GPGSID>
        public const string achievement_100_rabbits_every_time = "CgkI09n5uP8HEAIQHg"; // <GPGSID>
        public const string leaderboard_level = "CgkI09n5uP8HEAIQAQ"; // <GPGSID>
        public const string achievement_30000_points = "CgkI09n5uP8HEAIQJQ"; // <GPGSID>
        public const string achievement_1000_rabbits_every_time = "CgkI09n5uP8HEAIQGw"; // <GPGSID>
        public const string achievement_level_10 = "CgkI09n5uP8HEAIQCg"; // <GPGSID>
        public const string achievement_15_pillows = "CgkI09n5uP8HEAIQFg"; // <GPGSID>
        public const string achievement_5_colored_eggs = "CgkI09n5uP8HEAIQGA"; // <GPGSID>
        public const string achievement_use_a_pillow = "CgkI09n5uP8HEAIQFA"; // <GPGSID>
        public const string achievement_5000_points = "CgkI09n5uP8HEAIQBw"; // <GPGSID>
        public const string achievement_use_a_slug = "CgkI09n5uP8HEAIQEQ"; // <GPGSID>
        public const string achievement_5_slugs = "CgkI09n5uP8HEAIQEg"; // <GPGSID>
        public const string achievement_save_10000_eggs = "CgkI09n5uP8HEAIQJA"; // <GPGSID>
        public const string achievement_use_colored_eggs = "CgkI09n5uP8HEAIQFw"; // <GPGSID>
        public const string achievement_level_50 = "CgkI09n5uP8HEAIQDQ"; // <GPGSID>
        public const string achievement_use_a_rabbit = "CgkI09n5uP8HEAIQDg"; // <GPGSID>
        public const string achievement_100_points = "CgkI09n5uP8HEAIQBA"; // <GPGSID>
        public const string achievement_100_colored_eggs_every_time = "CgkI09n5uP8HEAIQHw"; // <GPGSID>
        public const string achievement_1000_colored_eggs_every_time = "CgkI09n5uP8HEAIQGg"; // <GPGSID>
        public const string achievement_7500_points = "CgkI09n5uP8HEAIQCQ"; // <GPGSID>
        public const string achievement_2000_points = "CgkI09n5uP8HEAIQBg"; // <GPGSID>
        public const string achievement_5_rabbits = "CgkI09n5uP8HEAIQDw"; // <GPGSID>
        public const string achievement_15_slugs = "CgkI09n5uP8HEAIQEw"; // <GPGSID>
        public const string achievement_120000_points = "CgkI09n5uP8HEAIQJw"; // <GPGSID>
        public const string achievement_level_20 = "CgkI09n5uP8HEAIQCw"; // <GPGSID>
        public const string achievement_100_pillows_every_time = "CgkI09n5uP8HEAIQIQ"; // <GPGSID>
        public const string achievement_save_50000_eggs = "CgkI09n5uP8HEAIQIw"; // <GPGSID>
        public const string leaderboard_points = "CgkI09n5uP8HEAIQAA"; // <GPGSID>

}

